### ISSUE TITLE
Feature: access to commandTag would be very convenient, especially for e.g. "AffectedRows"

### ISSUE THREAD

**Issue by ppenguin** [wcamarao/pmx#1]
I like the (very) lean premise of `pmx`, since it enables us to avoid bloated ORMs. 

However, the fact that for e.g. an `pmx.Update` query there is no return value that enables us to see whether there was in fact an update (i.e. "RowsAffected") is problematic, since usually one would like to make this distinction (additionally to error/no-error).

So it would be better to have either (always/optionally?) `commandTag` returned, or have an additional `Update` wrapper that can be chosen to get more feedback.

**Comment by wcamarao** [comment]
Thanks @ppenguin and that makes sense to me as well. I've pushed an update exposing `pgconn.CommandTag` from `Insert` and `Update` functions.

**Comment by ppenguin** [comment]
@wcamarao cool! I made a quick hack in a fork for that feature but forgot about PR'ing (it was hacky anyway) your solution seems to be solid, I haven't tested it but from the code it seems to cover this issue completely. So closing this...
Thanks!
