### ISSUE TITLE
Insert() and returning filled in autogenerated fields?

### ISSUE THREAD

**Issue by mnestor** [wcamarao/pmx#2]
If I'm calling Insert and passing a struct is it possible to get it to return with the autogenerated fields filled in?

```
type Request struct {
	ID        uuid.UUID `json:"-" generated:"auto" db:"id" table:"sign_request_user"`
	Request string    `json:"request" db:"request"`
	Created   time.Time `json:"-" generated:"auto" db:"-"`
	Updated   time.Time `json:"-" generated:"auto" db:"-"`
	Status    string    `json:"-" generated:"auto" db:"-"`
```

So I insert just the Request value into the struct and would get back filled in ID, Status and such.

**Comment by wcamarao** [comment]
Looking into your PR and happy to add support for this. Let's continue the conversation in the PR. Thanks
