### ISSUE TITLE
Scan with join

### ISSUE THREAD

**Issue by defany** [wcamarao/pmx#4]
```golang
type B struct {
	Type   string             `db:"type" table:"games_bets"`
	Game   Game               `db:"" table:"games"`
	User   storusermodel.User `db:"" table:"users"`
	Amount float64            `db:"amount"`
	Value  string             `db:"value"`
}
```

I have this struct, how i can scan into Game and User?

**Comment by wcamarao** [comment]
Remove the multiple `table` struct tags since that's only used for insert. Do your joined query and scan it into the annotated struct normally. Just make sure to match the `db` struct tags with the joined query returned columns.
