### ISSUE TITLE
(Try to) upstream functionality to pgx

### ISSUE THREAD

**Issue by pathob** [wcamarao/pmx#5]
Hi, I've stumbled over your library while searching for how to use the pgx struct tags with insert / update operations. In my opinion the pgx functionality is quite incomplete because it only allows for scanning. Don't you think it would be a better idea to try to upstream the functionality of your library to the pgx project?

**Comment by wcamarao** [comment]
Thanks for the suggestion and sorry I don't think that makes sense. There are two library families in there: one hosted by the pgx core maintainer, and another one hosted by additional contributors.
