### ISSUE TITLE
Support INSERT .. ON CONFLICT

### ISSUE THREAD

**Issue by kerma** [wcamarao/pmx#6]
https://www.postgresql.org/docs/current/sql-insert.html#SQL-ON-CONFLICT

Instead of relying on duplicate key errors I'd like to use ON CONFLICT DO NOTHING and CommandTag.RowsAffected(). 

Also, as Update() seems to be removed (I'm currently on v0.0.0-20230325043427-5b6ceb086444) DO UPDATE would probably be also useful.

**Comment by wcamarao** [comment]
Thanks for the suggestion @kerma. Confirming update has been removed and 'on conflict' is out of scope for this module.
